words = [
    "fmax",
    "fmin",
    "hilfsskripte",
    "hochzuladen",
    "mels",
    "programmierstyle",
    "seedlist",
    "sinipits",
    "skripte",
    "svgwrite",
]
ignore_paths = ["pyproject.toml"]
