[style]
    seed = 23
    seedlist = [2822, 406, 1079, 4, 29, 93874, 33]


[pic_scripts]
    blobs_only = false
    geometric_patterns = false
    line_cuts = false
    organic_flowfield = false
    organic_with_blobs = false
    random_walk_lines = false
    solid_objects_3d = true


[colors]
    bg = "#F5FBE6"
    black = "#000000"
    c1 = "#215E61"
    c2 = "#233D4D"
    c3 = "#FE7F2D"
    stroke = "#233D4D"
