[style]
    seed = 23


[pic_scripts]
    blobs_only = true
    geometric_patterns = false
    organic_flowfield = false
    organic_with_blobs = false


[colors]
    bg = "#F5FBE6"
    black = "#000000"
    c1 = "#215E61"
    c2 = "#233D4D"
    c3 = "#FE7F2D"
    stroke = "#233D4D"
