[style]
    seed = 23
    seedlist = [2822, 406, 1079, 7345, 3359, 3197, 3918, 1815]


[pic_scripts]
    blobs_only = true
    geometric_patterns = true
    organic_flowfield = true
    organic_with_blobs = true


[colors]
    bg = "#F5FBE6"
    black = "#000000"
    c1 = "#215E61"
    c2 = "#233D4D"
    c3 = "#FE7F2D"
    stroke = "#233D4D"
