[project]
name = "generative-cover"
version = "0.1.0"
description = "python scripts to generate generative pictures"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cairosvg>=2.7.1",
    "samila>=1.6",
    "shapely>=2.0.3",
    "svgwrite>=1.4.3",
]
