[project]
name = "generative-cover"
version = "0.1.0"
description = "python scripts to generate generative pictures"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "svgwrite>=1.4.3",
]
